# Tensor数据类型 
+ tf.constant(a):常量 普通tensor
+ tf.is_tensor(a)//instance(x,type):判断类型
+ tf.conver_to_tensor(x,dtype=tf.int32):numpy转为tenso
+ tf.cast(x,dtype=bool):tensor内部类型转换
+ tf.constant(a).numpy()tensor转为numpy

In [1]:
import tensorflow as tf

In [3]:
# tensor的定义

# tf.constant(1)
# #<tf.Tensor: shape=(), dtype=int32, numpy=1> 整形常量
# tf.constant(1.)
# # <tf.Tensor: shape=(), dtype=float32, numpy=1.0> 浮点常量
tf.constant([True,False])
tf.constant("hello world")

<tf.Tensor: id=3, shape=(), dtype=string, numpy=b'hello world'>

In [4]:
#tensor的属性

a = tf.constant(1)
#a.dtype
#tf.is_tensor(a)
#isinstance(a,tf.tensor)
a = tf.cast(a,dtype=tf.float16)
a.dtype

tf.float16

In [5]:
# 数据类型转化 

# tf.Variable
a = tf.range(5) #numpy=array([0, 1, 2, 3, 4])
b = tf.Variable(a) #自动进行求导
b.name #'Variable:0' 记录a的求导属性

'Variable:0'

## tensor 转为 numpy

In [6]:
# tensor 转为 numpy

a = tf.range(5)
a.numpy() #a本身的属性是没有改变  依旧是tensor


array([0, 1, 2, 3, 4])

# 创建 Tensor
+ tf.zeros:float32 0
+ tf.ones:float32 1
+ tf.fill([形状],a):创建值为a的、形状为[]的tensor
+ tf.random.normal([],mean=a,stddev=b)：创建均值为a 方差为b的正态分布tensor
+ tf.random.uniform([],minval=a,maxval=b)：创建[a,b]区间的均匀分布矩阵
+ tf.random.shuffle(a):打乱顺序
+ tf.gather(a,idx):按照idx重塑数据a
+ tf.ont_hot(x,depth=10):深度为10的连1矩阵
+ tf.keras.losses.mse(label,out):求mse 

## numpy list 

In [2]:
import tensorflow as tf
import numpy as np

tf.convert_to_tensor(np.zeros([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

## zeros ones fill

zeros(同ones)
<br> 使用tf.zeros()创建float32类型数据  转类型的话会变为int32

In [3]:
#zeros 创建规定行列的矩阵 (类型为float32 值为0)

#tf.zeros([])
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [4]:
a = tf.constant([0])
tf.zeros_like(a) #等价为tf.zeros(a.ashape) 

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0])>

In [5]:
#fill

tf.fill([2,3],0) #dtype=int32

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

## random

In [6]:
#正态分布 均值为1 方差为1
tf.random.normal([2,2],mean=1,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.7395563, 1.5155125],
       [3.4605916, 1.0846611]], dtype=float32)>

In [7]:
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.24354562,  1.3536524 ],
       [-1.5167385 , -1.1512249 ]], dtype=float32)>

In [ ]:
#截断的正太分布
tf.random.truncated_normal([2,2],mean=0,stddev=1)

+ 截断分布是指，限制变量x 取值范围(scope)的一种分布。例如，限制x取值在0到50之间，即{0<x<50}。因此，根据限制条件的不同，截断分布可以分为：
    + 限制取值上限，例如，负无穷<x<50
    + 限制取值下限，例如，0<x<正无穷
    + 上限下限取值都限制，例如，0<x<50

In [10]:
# 均匀分布
tf.random.uniform([2,2],minval=0,maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[57,  4],
       [98, 73]])>

In [18]:
## 打断idx后  a,b索引不变

idx = tf.range(10)
idx = tf.random.shuffle(idx)
idx
# idx  <tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 0, 3, 6, 7, 4, 2, 9, 8, 1])>

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 7, 3, 6, 1, 9, 8, 0, 5, 4])>

In [19]:
a = tf.random.normal([10,784])
b = tf.random.uniform([10],maxval=10,dtype=tf.int32)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 4, 5, 7, 2, 2, 6, 7, 5, 6])>

In [20]:
#根据规定好的索引来收集数据
a = tf.gather(a,idx)
b = tf.gather(b,idx)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 7, 7, 6, 4, 6, 5, 6, 2, 2])>

## loss计算 

In [21]:
# 无bias的loss

out = tf.random.uniform([4,10])
out

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.91706014, 0.6028607 , 0.94118524, 0.6287633 , 0.20673192,
        0.3472966 , 0.23640132, 0.7508693 , 0.17707789, 0.827335  ],
       [0.29381335, 0.49683583, 0.07704091, 0.7920108 , 0.07193172,
        0.90723515, 0.5830134 , 0.35412967, 0.2655207 , 0.1540463 ],
       [0.9750924 , 0.8159231 , 0.32416308, 0.5775384 , 0.8204012 ,
        0.2860775 , 0.9213507 , 0.53774893, 0.41607523, 0.17705369],
       [0.5273237 , 0.7081882 , 0.30076587, 0.50427234, 0.5887846 ,
        0.2800244 , 0.00454199, 0.19444561, 0.5863639 , 0.34619105]],
      dtype=float32)>

In [26]:
y = tf.range(4)
y = tf.one_hot(y,depth=10) #返回one-hot张量
y

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [27]:
loss = tf.keras.losses.mse(y,out)
loss

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.3150376 , 0.23605108, 0.45042676, 0.20423885], dtype=float32)>

In [28]:
tf.reduce_mean(loss)

<tf.Tensor: shape=(), dtype=float32, numpy=0.30143857>

# 索引和切片 
+ a.shape：查看tensor属性
+ a[::-1]：倒序
+ tf.gather(x,axis=0,indices=[]):收集特定行
+ tf.gather_nd(x,[])取某一维度xx

## numpy 索引

In [36]:
import tensorflow as tf
a = tf.ones([1,5,5,3])
a[0][4]
a[0][0][0]
a[0][0][0][2]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [44]:
#切片 

#一维切片 同numpy
a = tf.range(10)
a[-1:] 
a[-2:]

#倒序
a[::-1] #[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
a[::-2] #[9, 7, 5, 3, 1]
a[2::-2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0])>

In [38]:
#二维切片
a = tf.random.normal([1,5,5,3])
a.shape

TensorShape([1, 5, 5, 3])

In [39]:
a[0].shape #等同于a[0,:,:,:].shape

TensorShape([5, 5, 3])

## **...省略号 同前**

In [45]:
a = tf.random.normal([1,4,3,2,1])
a.shape

TensorShape([1, 4, 3, 2, 1])

In [47]:
a[0,...].shape

TensorShape([4, 3, 2, 1])

## selecting indexing
+ gather 收集特定行 维数大于目标便显示全部
+ gather_nd 选择某一维度


In [51]:
a = tf.random.normal([5,4,3])
a.shape

TensorShape([5, 4, 3])

In [52]:
tf.gather(a,axis=0,indices=[2,3]).shape

TensorShape([2, 4, 3])

In [55]:
tf.gather_nd(a,[0]).shape #[[0] [] []]

TensorShape([4, 3])

# 维度变化 
+ a.shape a.ndim :属性 维度
+ tf.reshape(x,[]):将tensor x转化为[]形状
+ tf.transpose(x,perm=[]):按照索引转化维度
+ tf.expend_dims(x,axis=0)：在axis前增加一个维度
+ tf.squeeze(x,axis=0):删除axis的维度(**如果没有axis 便删除维度1**)

## 图片视图
+ [b, 28, 28] # 保存b张图片，28行，28列（保存数据一般行优先），图片的数据没有被破坏
+ [b, 28*28] # 保存b张图片，不考虑图片的行和列，只保存图片的数据，不关注图片数据的细节
+ [b, 2, 14*28] # 保存b张图片，把图片分为上下两个部分，两个部分具体多少行是不清楚的
+ [b, 28, 28, 1] # 保存b张图片，28行，28列，1个通道

## Reshape(重塑视图)

In [56]:
a = tf.random.normal([4,28,28,3])
print(a.shape,a.ndim)

(4, 28, 28, 3) 4


In [57]:
tf.reshape(a,[4,784,3]).shape #给出一张图片某个通道的数据 丢失行、宽的信息
#等同于 tf.reshape(a,[4,-1,3]).shape # 4*(-1)*3=4*28*28*3

TensorShape([4, 784, 3])

In [58]:
tf.reshape(a,[4,784*3]).shape #给出一张图所有信息 地市行、宽、通道的信息
#等同于 tf.reshape(a,[4,-1]).shape

TensorShape([4, 2352])

## Reshape(恢复视图)

In [59]:
# 两层封装
tf.reshape(tf.reshape(a,[4,-1]),[4,28,28,3]).shape

TensorShape([4, 28, 28, 3])

## Transpose 

In [60]:
a = tf.random.normal([4,3,2,1])
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [62]:
tf.transpose(a,perm=[0,1,3,2]).shape #按照索引进行转置 perm可以省略

TensorShape([4, 3, 1, 2])

## Expand_dims/Squeeze

In [ ]:
a = tf.random.normal([4,25,8])
tf.expand_dims(a,axis=0).shape #索引0前 axis控制增加维度位置
tf.expand_dims(a,axis=1).shape
tf.squeeze(a,axis=0).shape

# Broadcasting
+ 某一些方面 tensor之间可以相加
+ tf.broadcast_to(x,[]):将某维度扩展至[]形状
+ tf.tile(x，[a,b,c]):一维复制a次，二维复制b次，三维复制c次
<br>Broadingcasting可以理解为把维度分为大维度和小维度，小维度较为具体，大维度更加抽象

In [72]:
try:
    a = tf.random.normal([4,28,28,3])
    print((a+tf.random.normal([1,4,1,1])).shape)
except Exception as e:
    print(e)

Incompatible shapes: [4,28,28,3] vs. [1,4,1,1] [Op:AddV2]


In [73]:
b = tf.broadcast_to(tf.random.normal([4,1,1,1]),[4,28,28,3])
b.shape

TensorShape([4, 28, 28, 3])

In [77]:
a = tf.ones([3,4])
a1 = tf.broadcast_to(a,[2,3,4]) #TensorShape([2, 3, 4])
a2 = tf.expand_dims(a,axis=1) #TensorShape([1, 3, 4])
a2 = tf.tile(a2,[2,1,1]) #复制一维2次 二维1次 三维1次
a2.shape

TensorShape([6, 1, 4])

# 数学运算
+ +-*：各元素独立运算
+ **,square
+ sqrt,pow:tf.sqrt,tf.pow
+ //,%(整数除法，取余数)：每个元素独立运算
+ exp,log：tf.math.log,tf.exp
+ @,matmul(矩阵乘法)：tf.matul(x,y)
+ linear layer

In [85]:
import tensorflow as tf
x = tf.fill([2,2],2.) #注意要同类型相加减
y = tf.ones([2,2])

In [86]:
x+y x-y x*y x//y x%y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [87]:
y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [91]:
tf.math.log(y) #只有以e为底的log
tf.exp(y)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.7182817, 2.7182817],
       [2.7182817, 2.7182817]], dtype=float32)>

In [92]:
tf.pow(x,3)
tf.sqrt(x)
x**2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [93]:
y@x #等同于tf.matul(x,y)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [ ]:
#Y = X@W +b
x = tf.ones([4, 2])
W = tf.ones([2, 1])
b = tf.constant(0.1)  # 自动broadcast为[4,1]

x@W + b
